# Generated by Django 5.0.4 on 2026-06-12 00:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (Identificador URL)')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Idade (anos)')),
                ('guardian_name', models.CharField(max_length=100, verbose_name='Nome do responsável')),
                ('guardian_whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sessions_app.company')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Método')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='sessions_app.company')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='Duração (minutos)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='sessions_app.company')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['duration_minutes'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Aguardando início'), ('running', 'Em andamento'), ('paused', 'Pausado'), ('finished', 'Finalizado'), ('expired', 'Expirado (não retirado)')], default='waiting', max_length=10, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Pausado em')),
                ('total_paused_seconds', models.PositiveIntegerField(default=0, verbose_name='Segundos pausados')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name='Pagamento confirmado')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor pago')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sessions_app.child', verbose_name='Criança')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sessions_app.company')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions_app.paymentmethod', verbose_name='Forma de pagamento')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessions_app.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-created_at'],
            },
        ),
    ]
