# Generated by Django 5.0.4 on 2026-06-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='age',
        ),
    ]
