# Generated by Django 5.0.4 on 2026-06-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0002_remove_child_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='added_duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Tempo Extra (segundos)'),
        ),
    ]
