# Generated by Django 5.0.4 on 2026-06-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_session_added_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/WhatsApp'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_instance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instância Evolution'),
        ),
    ]
