# Generated by Django 5.0.4 on 2026-06-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0004_company_logo_company_phone_company_whatsapp_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do responsável'),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
