# Generated by Django 5.0.4 on 2026-06-23 18:29

import django.db.models.deletion
from django.db import migrations, models

def migrate_payments(apps, schema_editor):
    Session = apps.get_model('sessions_app', 'Session')
    SessionPayment = apps.get_model('sessions_app', 'SessionPayment')
    for session in Session.objects.filter(payment_method__isnull=False, amount_paid__isnull=False):
        SessionPayment.objects.create(
            session=session,
            payment_method=session.payment_method,
            amount=session.amount_paid
        )

class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0005_alter_child_guardian_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessions_app.paymentmethod', verbose_name='Forma de pagamento')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sessions_app.session', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Pagamento da Sessão',
                'verbose_name_plural': 'Pagamentos da Sessão',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(migrate_payments, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='session',
            name='payment_method',
        ),
    ]
